# Events service overview

The Events service in Coralogix provides programmatic access to events generated by alert-driven incidents. When an alert's conditions are met, an incident is triggered, and the system begins producing event notifications to inform users based on the alert's configured notification policy—unless the alert is in phantom mode (silent, no notifications). These events can be retrieved individually or in bulk, filtered by various fields, counted, and analyzed statistically. This service enables downstream systems to monitor alert-driven activity, audit incident behavior, and build custom observability tools.

Learn more about alerts in our [documentation](https://coralogix.com/docs/user-guides/alerting/introduction-to-alerts/).



## Common error response codes

| Status Code | Description                           |
|-------------|---------------------------------------|
| `400 Bad Request` | Response code 400 |
| `401 Unauthorized` | Response code 401 |
| `500 Internal Server Error` | Response code 500 |

## Constants

<details>
  <summary>OrderByFields</summary>

  | Value |
|-------|
| `ORDER_BY_FIELDS_UNSPECIFIED` |
| `ORDER_BY_FIELDS_TIMESTAMP` |
</details>
<details>
  <summary>OrderByDirection</summary>

  | Value |
|-------|
| `ORDER_BY_DIRECTION_UNSPECIFIED` |
| `ORDER_BY_DIRECTION_ASC` |
| `ORDER_BY_DIRECTION_DESC` |
</details>
<details>
  <summary>FilterOperator</summary>

  | Value |
|-------|
| `FILTER_OPERATOR_AND_OR_UNSPECIFIED` |
| `FILTER_OPERATOR_OR` |
</details>
<details>
  <summary>FilterMatcher</summary>

  | Value |
|-------|
| `FILTER_MATCHER_TEXT_OR_UNSPECIFIED` |
| `FILTER_MATCHER_REGEXP` |
</details>
