#!/usr/bin/env python3
"""
Generate the public changelog (changelog.mdx) from the upstream cx-management-apis
CHANGELOG.md, unifying entries by *docs release date* instead of upstream date.

Upstream records changes under `## YYYY-MM-DD` headers (reverse-chronological), with
verbatim bullet entries. When a facade sync ships those changes to the public docs, every
upstream entry newer than what we've already published collapses into a single section
dated the release day.

State lives in changelog.data.json (the source of truth for released history); the
high-water mark is derived as max(upstream_dates) across all recorded releases.

Usage:
  python3 build_changelog.py \
    --upstream <path/to/CHANGELOG.md> \
    --release-date <YYYY-MM-DD> \
    --cx-sha <sha> \
    --data changelog.data.json \
    --out changelog.mdx \
    [--bootstrap]
"""

import argparse
import json
import re
import sys
from datetime import date, datetime
from pathlib import Path
from typing import List, Optional, Tuple

DATE_HEADER = re.compile(r"^##\s+(\d{4}-\d{2}-\d{2})\s*$")
BULLET = re.compile(r"^-\s+")

FRONTMATTER = """---
title: Changelog
description: "Public API changes, grouped by Coralogix Developer Docs release date."
---

<Note>
  Entries are sourced verbatim from the upstream API changelog and grouped by the date
  they were published to these docs. A single release may bundle changes recorded
  upstream across several days.
</Note>

"""


def parse_upstream(text: str) -> List[Tuple[str, List[str]]]:
    """Parse upstream CHANGELOG.md into ordered (date, [bullets]) preserving file order.

    Bullets may span multiple lines; continuation lines (indented or non-empty,
    non-header, non-bullet) are folded into the current bullet verbatim.
    """
    sections: List[Tuple[str, List[str]]] = []
    cur_date: Optional[str] = None
    cur_bullets: List[str] = []
    cur_bullet: Optional[List[str]] = None

    def flush_bullet():
        nonlocal cur_bullet
        if cur_bullet is not None:
            cur_bullets.append("\n".join(cur_bullet).rstrip())
            cur_bullet = None

    def flush_section():
        nonlocal cur_date, cur_bullets
        flush_bullet()
        if cur_date is not None:
            sections.append((cur_date, cur_bullets))
        cur_date = None
        cur_bullets = []

    for line in text.splitlines():
        m = DATE_HEADER.match(line)
        if m:
            flush_section()
            cur_date = m.group(1)
            cur_bullets = []
            continue
        if cur_date is None:
            continue  # skip the top-level "# Changelog" header and any preamble
        if BULLET.match(line):
            flush_bullet()
            cur_bullet = [BULLET.sub("", line, count=1).rstrip()]
        elif line.strip() == "":
            flush_bullet()
        elif cur_bullet is not None:
            cur_bullet.append(line.strip())
        # else: stray text outside a bullet -> ignore

    flush_section()
    return sections


def load_data(path: Path) -> List[dict]:
    if not path.exists():
        return []
    return json.loads(path.read_text(encoding="utf-8"))


def high_water_mark(data: List[dict]) -> Optional[str]:
    """Latest upstream date already published, across all release records."""
    dates = [d for rec in data for d in rec.get("upstream_dates", [])]
    return max(dates) if dates else None


def collect_new(
    sections: List[Tuple[str, List[str]]], hwm: Optional[str]
) -> Tuple[List[str], List[str]]:
    """Return (new_bullets in upstream order, sorted unique upstream_dates consumed)."""
    new_bullets: List[str] = []
    new_dates: List[str] = []
    for dt, bullets in sections:
        if hwm is None or dt > hwm:
            new_bullets.extend(bullets)
            if bullets:
                new_dates.append(dt)
    return new_bullets, sorted(set(new_dates), reverse=True)


def fmt_label(iso: str) -> str:
    return datetime.strptime(iso, "%Y-%m-%d").strftime("%B %-d, %Y")


def render(data: List[dict], cx_sha: str) -> str:
    out = [FRONTMATTER]
    for rec in data:
        if not rec.get("bullets"):
            continue  # skip bootstrap/sentinel records with no published entries
        out.append(f'<Update label="{fmt_label(rec["release_date"])}">\n')
        for b in rec["bullets"]:
            # Keep multi-line bullets readable under the markdown list item.
            lines = b.split("\n")
            out.append(f"  - {lines[0]}")
            for cont in lines[1:]:
                out.append(f"    {cont}")
        out.append("\n</Update>\n")
    if cx_sha:
        out.append(
            f"\n{{/* Generated by build_changelog.py from cx-management-apis@{cx_sha} */}}\n"
        )
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream", required=True, type=Path)
    ap.add_argument("--release-date", default=date.today().isoformat())
    ap.add_argument("--cx-sha", default="")
    ap.add_argument("--data", default="changelog.data.json", type=Path)
    ap.add_argument("--out", default="changelog.mdx", type=Path)
    ap.add_argument(
        "--bootstrap",
        action="store_true",
        help="Seed the high-water mark from current upstream without emitting a release.",
    )
    args = ap.parse_args()

    sections = parse_upstream(args.upstream.read_text(encoding="utf-8"))
    data = load_data(args.data)

    if args.bootstrap:
        if data:
            print("Data file already exists; refusing to bootstrap over it.", file=sys.stderr)
            return 1
        all_dates = sorted({dt for dt, _ in sections}, reverse=True)
        seed = {
            "release_date": args.release_date,
            "upstream_dates": all_dates,  # marks everything as already published
            "bullets": [],  # sentinel: nothing rendered
        }
        args.data.write_text(json.dumps([seed], indent=2) + "\n", encoding="utf-8")
        if not args.out.exists():
            args.out.write_text(render([seed], args.cx_sha), encoding="utf-8")
        print(f"Bootstrapped HWM at {high_water_mark([seed])} ({len(all_dates)} upstream dates).")
        return 0

    hwm = high_water_mark(data)
    new_bullets, new_dates = collect_new(sections, hwm)

    if not new_bullets:
        print("No new upstream entries since last release; nothing to do.")
        return 0

    # Most recent real (non-sentinel) record, for same-day merging.
    if data and data[0].get("release_date") == args.release_date:
        rec = data[0]
        rec["bullets"] = new_bullets + rec.get("bullets", [])
        rec["upstream_dates"] = sorted(
            set(rec.get("upstream_dates", [])) | set(new_dates), reverse=True
        )
        print(f"Merged {len(new_bullets)} entries into existing {args.release_date} release.")
    else:
        data.insert(
            0,
            {
                "release_date": args.release_date,
                "upstream_dates": new_dates,
                "bullets": new_bullets,
            },
        )
        print(f"Added {args.release_date} release with {len(new_bullets)} entries.")

    args.data.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    args.out.write_text(render(data, args.cx_sha), encoding="utf-8")
    print(f"Wrote {args.out} and {args.data}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
